ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
irise_llama-irise_llama-1  | Traceback (most recent call last):
irise_llama-irise_llama-1  |   File "/usr/local/bin/uvicorn", line 8, in <module>
irise_llama-irise_llama-1  |     sys.exit(main())
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
irise_llama-irise_llama-1  |     return self.main(*args, **kwargs)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
irise_llama-irise_llama-1  |     rv = self.invoke(ctx)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
irise_llama-irise_llama-1  |     return ctx.invoke(self.callback, **ctx.params)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
irise_llama-irise_llama-1  |     return __callback(*args, **kwargs)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 404, in main
irise_llama-irise_llama-1  |     run(
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
irise_llama-irise_llama-1  |     server.run()
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
irise_llama-irise_llama-1  |     return asyncio.run(self.serve(sockets=sockets))
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
irise_llama-irise_llama-1  |     return loop.run_until_complete(main)
irise_llama-irise_llama-1  |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
irise_llama-irise_llama-1  |     config.load()
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 477, in load
irise_llama-irise_llama-1  |     self.loaded_app = import_from_string(self.app)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
irise_llama-irise_llama-1  |     raise exc from None
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
irise_llama-irise_llama-1  |     module = importlib.import_module(module_str)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
irise_llama-irise_llama-1  |     return _bootstrap._gcd_import(name[level:], package, level)
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
irise_llama-irise_llama-1  |   File "/app/./app.py", line 2, in <module>
irise_llama-irise_llama-1  |     from vllm import LLM
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/vllm/__init__.py", line 3, in <module>
irise_llama-irise_llama-1  |     from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 6, in <module>
irise_llama-irise_llama-1  |     from vllm.config import (CacheConfig, ModelConfig, ParallelConfig,
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/vllm/config.py", line 9, in <module>
irise_llama-irise_llama-1  |     from vllm.utils import get_cpu_memory, is_hip
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/vllm/utils.py", line 11, in <module>
irise_llama-irise_llama-1  |     from vllm._C import cuda_utils
irise_llama-irise_llama-1  | ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
irise_llama-irise_llama-1  | Traceback (most recent call last):
irise_llama-irise_llama-1  |   File "/usr/local/bin/uvicorn", line 8, in <module>
irise_llama-irise_llama-1  |     sys.exit(main())
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
irise_llama-irise_llama-1  |     return self.main(*args, **kwargs)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
irise_llama-irise_llama-1  |     rv = self.invoke(ctx)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
irise_llama-irise_llama-1  |     return ctx.invoke(self.callback, **ctx.params)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
irise_llama-irise_llama-1  |     return __callback(*args, **kwargs)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 404, in main
irise_llama-irise_llama-1  |     run(
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
irise_llama-irise_llama-1  |     server.run()
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
irise_llama-irise_llama-1  |     return asyncio.run(self.serve(sockets=sockets))
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
irise_llama-irise_llama-1  |     return loop.run_until_complete(main)
irise_llama-irise_llama-1  |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
irise_llama-irise_llama-1  |     config.load()
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 477, in load
irise_llama-irise_llama-1  |     self.loaded_app = import_from_string(self.app)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
irise_llama-irise_llama-1  |     raise exc from None
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
irise_llama-irise_llama-1  |     module = importlib.import_module(module_str)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
irise_llama-irise_llama-1  |     return _bootstrap._gcd_import(name[level:], package, level)
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
irise_llama-irise_llama-1  |   File "/app/./app.py", line 2, in <module>
irise_llama-irise_llama-1  |     from vllm import LLM
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/vllm/__init__.py", line 3, in <module>
irise_llama-irise_llama-1  |     from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 6, in <module>
irise_llama-irise_llama-1  |     from vllm.config import (CacheConfig, ModelConfig, ParallelConfig,
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/vllm/config.py", line 9, in <module>
irise_llama-irise_llama-1  |     from vllm.utils import get_cpu_memory, is_hip
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/vllm/utils.py", line 11, in <module>
irise_llama-irise_llama-1  |     from vllm._C import cuda_utils
irise_llama-irise_llama-1  | ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
irise_llama-irise_llama-1  | Traceback (most recent call last):
irise_llama-irise_llama-1  |   File "/usr/local/bin/uvicorn", line 8, in <module>
irise_llama-irise_llama-1  |     sys.exit(main())
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
irise_llama-irise_llama-1  |     return self.main(*args, **kwargs)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
irise_llama-irise_llama-1  |     rv = self.invoke(ctx)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
irise_llama-irise_llama-1  |     return ctx.invoke(self.callback, **ctx.params)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
irise_llama-irise_llama-1  |     return __callback(*args, **kwargs)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 404, in main
irise_llama-irise_llama-1  |     run(
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
irise_llama-irise_llama-1  |     server.run()
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
irise_llama-irise_llama-1  |     return asyncio.run(self.serve(sockets=sockets))
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
irise_llama-irise_llama-1  |     return loop.run_until_complete(main)
irise_llama-irise_llama-1  |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
irise_llama-irise_llama-1  |     config.load()
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 477, in load
irise_llama-irise_llama-1  |     self.loaded_app = import_from_string(self.app)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
irise_llama-irise_llama-1  |     raise exc from None
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
irise_llama-irise_llama-1  |     module = importlib.import_module(module_str)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
irise_llama-irise_llama-1  |     return _bootstrap._gcd_import(name[level:], package, level)
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
irise_llama-irise_llama-1  |   File "/app/./app.py", line 2, in <module>
irise_llama-irise_llama-1  |     from vllm import LLM
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/vllm/__init__.py", line 3, in <module>
irise_llama-irise_llama-1  |     from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 6, in <module>
irise_llama-irise_llama-1  |     from vllm.config import (CacheConfig, ModelConfig, ParallelConfig,
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/vllm/config.py", line 9, in <module>
irise_llama-irise_llama-1  |     from vllm.utils import get_cpu_memory, is_hip
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/vllm/utils.py", line 11, in <module>
irise_llama-irise_llama-1  |     from vllm._C import cuda_utils
irise_llama-irise_llama-1  | ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
irise_llama-irise_llama-1  | Traceback (most recent call last):
irise_llama-irise_llama-1  |   File "/usr/local/bin/uvicorn", line 8, in <module>
irise_llama-irise_llama-1  |     sys.exit(main())
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
irise_llama-irise_llama-1  |     return self.main(*args, **kwargs)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
irise_llama-irise_llama-1  |     rv = self.invoke(ctx)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
irise_llama-irise_llama-1  |     return ctx.invoke(self.callback, **ctx.params)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
irise_llama-irise_llama-1  |     return __callback(*args, **kwargs)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 404, in main
irise_llama-irise_llama-1  |     run(
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
irise_llama-irise_llama-1  |     server.run()
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
irise_llama-irise_llama-1  |     return asyncio.run(self.serve(sockets=sockets))
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
irise_llama-irise_llama-1  |     return loop.run_until_complete(main)
irise_llama-irise_llama-1  |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
irise_llama-irise_llama-1  |     config.load()
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 477, in load
irise_llama-irise_llama-1  |     self.loaded_app = import_from_string(self.app)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
irise_llama-irise_llama-1  |     raise exc from None
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
irise_llama-irise_llama-1  |     module = importlib.import_module(module_str)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
irise_llama-irise_llama-1  |     return _bootstrap._gcd_import(name[level:], package, level)
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
irise_llama-irise_llama-1  |   File "/app/./app.py", line 2, in <module>
irise_llama-irise_llama-1  |     from vllm import LLM
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/vllm/__init__.py", line 3, in <module>
irise_llama-irise_llama-1  |     from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 6, in <module>
irise_llama-irise_llama-1  |     from vllm.config import (CacheConfig, ModelConfig, ParallelConfig,
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/vllm/config.py", line 9, in <module>
irise_llama-irise_llama-1  |     from vllm.utils import get_cpu_memory, is_hip
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/vllm/utils.py", line 11, in <module>
irise_llama-irise_llama-1  |     from vllm._C import cuda_utils
irise_llama-irise_llama-1  | ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
irise_llama-irise_llama-1  | Traceback (most recent call last):
irise_llama-irise_llama-1  |   File "/usr/local/bin/uvicorn", line 8, in <module>
irise_llama-irise_llama-1  |     sys.exit(main())
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
irise_llama-irise_llama-1  |     return self.main(*args, **kwargs)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
irise_llama-irise_llama-1  |     rv = self.invoke(ctx)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
irise_llama-irise_llama-1  |     return ctx.invoke(self.callback, **ctx.params)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
irise_llama-irise_llama-1  |     return __callback(*args, **kwargs)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 404, in main
irise_llama-irise_llama-1  |     run(
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
irise_llama-irise_llama-1  |     server.run()
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
irise_llama-irise_llama-1  |     return asyncio.run(self.serve(sockets=sockets))
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
irise_llama-irise_llama-1  |     return loop.run_until_complete(main)
irise_llama-irise_llama-1  |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
irise_llama-irise_llama-1  |     config.load()
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 477, in load
irise_llama-irise_llama-1  |     self.loaded_app = import_from_string(self.app)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
irise_llama-irise_llama-1  |     raise exc from None
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
irise_llama-irise_llama-1  |     module = importlib.import_module(module_str)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
irise_llama-irise_llama-1  |     return _bootstrap._gcd_import(name[level:], package, level)
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
irise_llama-irise_llama-1  |   File "/app/./app.py", line 2, in <module>
irise_llama-irise_llama-1  |     from vllm import LLM
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/vllm/__init__.py", line 3, in <module>
irise_llama-irise_llama-1  |     from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 6, in <module>
irise_llama-irise_llama-1  |     from vllm.config import (CacheConfig, ModelConfig, ParallelConfig,
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/vllm/config.py", line 9, in <module>
irise_llama-irise_llama-1  |     from vllm.utils import get_cpu_memory, is_hip
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/vllm/utils.py", line 11, in <module>
irise_llama-irise_llama-1  |     from vllm._C import cuda_utils
irise_llama-irise_llama-1  | ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
irise_llama-irise_llama-1  | Traceback (most recent call last):
irise_llama-irise_llama-1  |   File "/usr/local/bin/uvicorn", line 8, in <module>
irise_llama-irise_llama-1  |     sys.exit(main())
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
irise_llama-irise_llama-1  |     return self.main(*args, **kwargs)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
irise_llama-irise_llama-1  |     rv = self.invoke(ctx)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
irise_llama-irise_llama-1  |     return ctx.invoke(self.callback, **ctx.params)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
irise_llama-irise_llama-1  |     return __callback(*args, **kwargs)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 404, in main
irise_llama-irise_llama-1  |     run(
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
irise_llama-irise_llama-1  |     server.run()
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
irise_llama-irise_llama-1  |     return asyncio.run(self.serve(sockets=sockets))
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
irise_llama-irise_llama-1  |     return loop.run_until_complete(main)
irise_llama-irise_llama-1  |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
irise_llama-irise_llama-1  |     config.load()
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 477, in load
irise_llama-irise_llama-1  |     self.loaded_app = import_from_string(self.app)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
irise_llama-irise_llama-1  |     raise exc from None
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
irise_llama-irise_llama-1  |     module = importlib.import_module(module_str)
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
irise_llama-irise_llama-1  |     return _bootstrap._gcd_import(name[level:], package, level)
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
irise_llama-irise_llama-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
irise_llama-irise_llama-1  |   File "/app/./app.py", line 2, in <module>
irise_llama-irise_llama-1  |     from vllm import LLM
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/vllm/__init__.py", line 3, in <module>
irise_llama-irise_llama-1  |     from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 6, in <module>
irise_llama-irise_llama-1  |     from vllm.config import (CacheConfig, ModelConfig, ParallelConfig,
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/vllm/config.py", line 9, in <module>
irise_llama-irise_llama-1  |     from vllm.utils import get_cpu_memory, is_hip
irise_llama-irise_llama-1  |   File "/usr/local/lib/python3.10/site-packages/vllm/utils.py", line 11, in <module>
irise_llama-irise_llama-1  |     from vllm._C import cuda_utils
irise_llama-irise_llama-1  | ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
irise_llama-irise_llama-1 exited with code 1


